// The language catalogue, shared by the renderer (picker) and the stack
// (prompt building) — src/stack/service.js already imports config/filters.js,
// so pure data crossing that line is established practice. One table means the
// picker can never offer a language the prompt builder cannot name.
//
// Scope = what Google Translate supports. Google is enabled by default, needs
// no key, and google-translate.js passes unmapped codes straight through
// (`mapping[code] || code`), so every entry here works out of the box without
// a single per-provider mapping. Sources with narrower coverage (DeepL) reject
// what they cannot do and the chain moves on.
//
// Fields:
//   code   what we send to providers, and the key everything else joins on
//   name   Chinese display name
//   nativeName endonym, shown beside the label
//   en     English name — also the letter-index key for the English UI
//
// MAINTENANCE: `npm run check:languages` keeps this in sync with the provider
// maps. `node scripts/verify-google-languages.mjs` asks Google to translate a
// sample into every code and reports the ones it rejects — run that after
// adding entries rather than trusting a code by eye.

export const LANGUAGES = [
  { code: 'auto', name: '自动检测', nativeName: 'Auto Detect', en: 'Auto Detect' },

  { code: 'af', name: '南非荷兰语', nativeName: 'Afrikaans', en: 'Afrikaans' },
  { code: 'sq', name: '阿尔巴尼亚语', nativeName: 'Shqip', en: 'Albanian' },
  { code: 'am', name: '阿姆哈拉语', nativeName: 'አማርኛ', en: 'Amharic' },
  { code: 'ar', name: '阿拉伯语', nativeName: 'العربية', en: 'Arabic' },
  { code: 'hy', name: '亚美尼亚语', nativeName: 'Հայերեն', en: 'Armenian' },
  { code: 'as', name: '阿萨姆语', nativeName: 'অসমীয়া', en: 'Assamese' },
  { code: 'ay', name: '艾马拉语', nativeName: 'Aymar aru', en: 'Aymara' },
  { code: 'az', name: '阿塞拜疆语', nativeName: 'Azərbaycan', en: 'Azerbaijani' },
  { code: 'bm', name: '班巴拉语', nativeName: 'Bamanankan', en: 'Bambara' },
  { code: 'eu', name: '巴斯克语', nativeName: 'Euskara', en: 'Basque' },
  { code: 'be', name: '白俄罗斯语', nativeName: 'Беларуская', en: 'Belarusian' },
  { code: 'bn', name: '孟加拉语', nativeName: 'বাংলা', en: 'Bengali' },
  { code: 'bho', name: '博杰普尔语', nativeName: 'भोजपुरी', en: 'Bhojpuri' },
  { code: 'bs', name: '波斯尼亚语', nativeName: 'Bosanski', en: 'Bosnian' },
  { code: 'bg', name: '保加利亚语', nativeName: 'Български', en: 'Bulgarian' },
  { code: 'ca', name: '加泰罗尼亚语', nativeName: 'Català', en: 'Catalan' },
  { code: 'ceb', name: '宿务语', nativeName: 'Cebuano', en: 'Cebuano' },
  { code: 'ny', name: '齐切瓦语', nativeName: 'Chichewa', en: 'Chichewa' },
  { code: 'zh', name: '中文', nativeName: '中文', en: 'Chinese' },
  { code: 'zh-TW', name: '繁体中文', nativeName: '繁體中文', en: 'Chinese (Traditional)' },
  { code: 'co', name: '科西嘉语', nativeName: 'Corsu', en: 'Corsican' },
  { code: 'hr', name: '克罗地亚语', nativeName: 'Hrvatski', en: 'Croatian' },
  { code: 'cs', name: '捷克语', nativeName: 'Čeština', en: 'Czech' },
  { code: 'da', name: '丹麦语', nativeName: 'Dansk', en: 'Danish' },
  { code: 'dv', name: '迪维希语', nativeName: 'ދިވެހި', en: 'Dhivehi' },
  { code: 'doi', name: '多格拉语', nativeName: 'डोगरी', en: 'Dogri' },
  { code: 'nl', name: '荷兰语', nativeName: 'Nederlands', en: 'Dutch' },
  { code: 'en', name: '英语', nativeName: 'English', en: 'English' },
  { code: 'eo', name: '世界语', nativeName: 'Esperanto', en: 'Esperanto' },
  { code: 'et', name: '爱沙尼亚语', nativeName: 'Eesti', en: 'Estonian' },
  { code: 'ee', name: '埃维语', nativeName: 'Eʋegbe', en: 'Ewe' },
  { code: 'tl', name: '菲律宾语', nativeName: 'Filipino', en: 'Filipino' },
  { code: 'fi', name: '芬兰语', nativeName: 'Suomi', en: 'Finnish' },
  { code: 'fr', name: '法语', nativeName: 'Français', en: 'French' },
  { code: 'fy', name: '弗里西语', nativeName: 'Frysk', en: 'Frisian' },
  { code: 'gl', name: '加利西亚语', nativeName: 'Galego', en: 'Galician' },
  { code: 'ka', name: '格鲁吉亚语', nativeName: 'ქართული', en: 'Georgian' },
  { code: 'de', name: '德语', nativeName: 'Deutsch', en: 'German' },
  { code: 'el', name: '希腊语', nativeName: 'Ελληνικά', en: 'Greek' },
  { code: 'gn', name: '瓜拉尼语', nativeName: 'Avañeẽ', en: 'Guarani' },
  { code: 'gu', name: '古吉拉特语', nativeName: 'ગુજરાતી', en: 'Gujarati' },
  { code: 'ht', name: '海地克里奥尔语', nativeName: 'Kreyòl ayisyen', en: 'Haitian Creole' },
  { code: 'ha', name: '豪萨语', nativeName: 'Hausa', en: 'Hausa' },
  { code: 'haw', name: '夏威夷语', nativeName: 'ʻŌlelo Hawaiʻi', en: 'Hawaiian' },
  { code: 'he', name: '希伯来语', nativeName: 'עברית', en: 'Hebrew' },
  { code: 'hi', name: '印地语', nativeName: 'हिन्दी', en: 'Hindi' },
  { code: 'hmn', name: '苗语', nativeName: 'Hmoob', en: 'Hmong' },
  { code: 'hu', name: '匈牙利语', nativeName: 'Magyar', en: 'Hungarian' },
  { code: 'is', name: '冰岛语', nativeName: 'Íslenska', en: 'Icelandic' },
  { code: 'ig', name: '伊博语', nativeName: 'Igbo', en: 'Igbo' },
  { code: 'ilo', name: '伊洛卡诺语', nativeName: 'Ilokano', en: 'Ilocano' },
  { code: 'id', name: '印尼语', nativeName: 'Bahasa Indonesia', en: 'Indonesian' },
  { code: 'ga', name: '爱尔兰语', nativeName: 'Gaeilge', en: 'Irish' },
  { code: 'it', name: '意大利语', nativeName: 'Italiano', en: 'Italian' },
  { code: 'ja', name: '日语', nativeName: '日本語', en: 'Japanese' },
  { code: 'jw', name: '爪哇语', nativeName: 'Basa Jawa', en: 'Javanese' },
  { code: 'kn', name: '卡纳达语', nativeName: 'ಕನ್ನಡ', en: 'Kannada' },
  { code: 'kk', name: '哈萨克语', nativeName: 'Қазақ тілі', en: 'Kazakh' },
  { code: 'km', name: '高棉语', nativeName: 'ភាសាខ្មែរ', en: 'Khmer' },
  { code: 'rw', name: '卢旺达语', nativeName: 'Kinyarwanda', en: 'Kinyarwanda' },
  { code: 'gom', name: '孔卡尼语', nativeName: 'कोंकणी', en: 'Konkani' },
  { code: 'ko', name: '韩语', nativeName: '한국어', en: 'Korean' },
  { code: 'kri', name: '克里奥尔语', nativeName: 'Krio', en: 'Krio' },
  { code: 'ku', name: '库尔德语', nativeName: 'Kurdî', en: 'Kurdish' },
  { code: 'ckb', name: '索拉尼库尔德语', nativeName: 'کوردیی ناوەندی', en: 'Kurdish (Sorani)' },
  { code: 'ky', name: '吉尔吉斯语', nativeName: 'Кыргызча', en: 'Kyrgyz' },
  { code: 'lo', name: '老挝语', nativeName: 'ລາວ', en: 'Lao' },
  { code: 'la', name: '拉丁语', nativeName: 'Latina', en: 'Latin' },
  { code: 'lv', name: '拉脱维亚语', nativeName: 'Latviešu', en: 'Latvian' },
  { code: 'ln', name: '林加拉语', nativeName: 'Lingála', en: 'Lingala' },
  { code: 'lt', name: '立陶宛语', nativeName: 'Lietuvių', en: 'Lithuanian' },
  { code: 'lg', name: '卢干达语', nativeName: 'Luganda', en: 'Luganda' },
  { code: 'lb', name: '卢森堡语', nativeName: 'Lëtzebuergesch', en: 'Luxembourgish' },
  { code: 'mk', name: '马其顿语', nativeName: 'Македонски', en: 'Macedonian' },
  { code: 'mai', name: '迈蒂利语', nativeName: 'मैथिली', en: 'Maithili' },
  { code: 'mg', name: '马达加斯加语', nativeName: 'Malagasy', en: 'Malagasy' },
  { code: 'ms', name: '马来语', nativeName: 'Bahasa Melayu', en: 'Malay' },
  { code: 'ml', name: '马拉雅拉姆语', nativeName: 'മലയാളം', en: 'Malayalam' },
  { code: 'mt', name: '马耳他语', nativeName: 'Malti', en: 'Maltese' },
  { code: 'mi', name: '毛利语', nativeName: 'Māori', en: 'Maori' },
  { code: 'mr', name: '马拉地语', nativeName: 'मराठी', en: 'Marathi' },
  { code: 'mni-Mtei', name: '曼尼普尔语', nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ', en: 'Meiteilon' },
  { code: 'lus', name: '米佐语', nativeName: 'Mizo ṭawng', en: 'Mizo' },
  { code: 'mn', name: '蒙古语', nativeName: 'Монгол', en: 'Mongolian' },
  { code: 'my', name: '缅甸语', nativeName: 'မြန်မာ', en: 'Myanmar' },
  { code: 'ne', name: '尼泊尔语', nativeName: 'नेपाली', en: 'Nepali' },
  { code: 'no', name: '挪威语', nativeName: 'Norsk', en: 'Norwegian' },
  { code: 'or', name: '奥里亚语', nativeName: 'ଓଡ଼ିଆ', en: 'Odia' },
  { code: 'om', name: '奥罗莫语', nativeName: 'Afaan Oromoo', en: 'Oromo' },
  { code: 'ps', name: '普什图语', nativeName: 'پښتو', en: 'Pashto' },
  { code: 'fa', name: '波斯语', nativeName: 'فارسی', en: 'Persian' },
  { code: 'pl', name: '波兰语', nativeName: 'Polski', en: 'Polish' },
  { code: 'pt', name: '葡萄牙语', nativeName: 'Português', en: 'Portuguese' },
  { code: 'pa', name: '旁遮普语', nativeName: 'ਪੰਜਾਬੀ', en: 'Punjabi' },
  { code: 'qu', name: '克丘亚语', nativeName: 'Runa Simi', en: 'Quechua' },
  { code: 'ro', name: '罗马尼亚语', nativeName: 'Română', en: 'Romanian' },
  { code: 'ru', name: '俄语', nativeName: 'Русский', en: 'Russian' },
  { code: 'sm', name: '萨摩亚语', nativeName: 'Gagana Sāmoa', en: 'Samoan' },
  { code: 'sa', name: '梵语', nativeName: 'संस्कृतम्', en: 'Sanskrit' },
  { code: 'gd', name: '苏格兰盖尔语', nativeName: 'Gàidhlig', en: 'Scots Gaelic' },
  { code: 'nso', name: '北索托语', nativeName: 'Sepedi', en: 'Sepedi' },
  { code: 'sr', name: '塞尔维亚语', nativeName: 'Српски', en: 'Serbian' },
  { code: 'st', name: '南索托语', nativeName: 'Sesotho', en: 'Sesotho' },
  { code: 'sn', name: '绍纳语', nativeName: 'ChiShona', en: 'Shona' },
  { code: 'sd', name: '信德语', nativeName: 'سنڌي', en: 'Sindhi' },
  { code: 'si', name: '僧伽罗语', nativeName: 'සිංහල', en: 'Sinhala' },
  { code: 'sk', name: '斯洛伐克语', nativeName: 'Slovenčina', en: 'Slovak' },
  { code: 'sl', name: '斯洛文尼亚语', nativeName: 'Slovenščina', en: 'Slovenian' },
  { code: 'so', name: '索马里语', nativeName: 'Soomaali', en: 'Somali' },
  { code: 'es', name: '西班牙语', nativeName: 'Español', en: 'Spanish' },
  { code: 'su', name: '巽他语', nativeName: 'Basa Sunda', en: 'Sundanese' },
  { code: 'sw', name: '斯瓦希里语', nativeName: 'Kiswahili', en: 'Swahili' },
  { code: 'sv', name: '瑞典语', nativeName: 'Svenska', en: 'Swedish' },
  { code: 'tg', name: '塔吉克语', nativeName: 'Тоҷикӣ', en: 'Tajik' },
  { code: 'ta', name: '泰米尔语', nativeName: 'தமிழ்', en: 'Tamil' },
  { code: 'tt', name: '鞑靼语', nativeName: 'Татарча', en: 'Tatar' },
  { code: 'te', name: '泰卢固语', nativeName: 'తెలుగు', en: 'Telugu' },
  { code: 'th', name: '泰语', nativeName: 'ไทย', en: 'Thai' },
  { code: 'ti', name: '提格利尼亚语', nativeName: 'ትግርኛ', en: 'Tigrinya' },
  { code: 'ts', name: '聪加语', nativeName: 'Xitsonga', en: 'Tsonga' },
  { code: 'tr', name: '土耳其语', nativeName: 'Türkçe', en: 'Turkish' },
  { code: 'tk', name: '土库曼语', nativeName: 'Türkmen', en: 'Turkmen' },
  { code: 'ak', name: '契维语', nativeName: 'Twi', en: 'Twi' },
  { code: 'uk', name: '乌克兰语', nativeName: 'Українська', en: 'Ukrainian' },
  { code: 'ur', name: '乌尔都语', nativeName: 'اردو', en: 'Urdu' },
  { code: 'ug', name: '维吾尔语', nativeName: 'ئۇيغۇرچە', en: 'Uyghur' },
  { code: 'uz', name: '乌兹别克语', nativeName: 'Oʻzbekcha', en: 'Uzbek' },
  { code: 'vi', name: '越南语', nativeName: 'Tiếng Việt', en: 'Vietnamese' },
  { code: 'cy', name: '威尔士语', nativeName: 'Cymraeg', en: 'Welsh' },
  { code: 'xh', name: '科萨语', nativeName: 'isiXhosa', en: 'Xhosa' },
  { code: 'yi', name: '意第绪语', nativeName: 'ייִדיש', en: 'Yiddish' },
  { code: 'yo', name: '约鲁巴语', nativeName: 'Yorùbá', en: 'Yoruba' },
  { code: 'zu', name: '祖鲁语', nativeName: 'isiZulu', en: 'Zulu' },
];

export const LANGUAGE_BY_CODE = Object.fromEntries(LANGUAGES.map((l) => [l.code, l]));

export function getLanguageName(code) {
  return LANGUAGE_BY_CODE[code]?.name || code;
}
